name: pathml

channels:
    - conda-forge
    - pytorch

dependencies:
    - pip==21.2.2
    - python==3.8
    - numpy==1.19.5
    - scipy==1.7.1
    - scikit-image==0.18.3
    - matplotlib==3.1.3
    - python-spams==2.6.1
    - openjdk==8.0.152
    - pytorch==1.9.0
    - h5py==3.1.0
    - dask==2021.7.1
    - pydicom==2.1.2
    - pytest==6.2.5
    - pre-commit==2.13.0
    - coverage==5.5
    - pip:
        - opencv-contrib-python==4.5.3.56
        - openslide-python==1.1.2
        - javabridge==1.0.19
        - python-bioformats==4.0.0
        - scanpy==1.7.2
        - anndata==0.7.6
        - ipython==7.27.0
        - sphinx==4.2.0
        - nbsphinx==0.8.7
        - nbsphinx-link==1.3.0
        - sphinx-rtd-theme==1.0.0
        - sphinx-autoapi==1.8.4
        - memory_profiler
