name: pathml

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - numpy>=1.18.1
  - matplotlib>=3.1.3
  - python-spams>=2.6.1
  - pip:
      - opencv-contrib-python>=4.1.1
      - openslide-python>=1.1.1
      - python-bioformats>=4.0.0
      - python-javabridge>=4.0.0
