name: pathml

channels:
    - conda-forge
    - pytorch

dependencies:
    - pip==21.2.2
    - python==3.8
    - numpy>=1.16.4,<1.19.0
    - scipy>=1.5.4
    - scikit-image>=0.16.2
    - matplotlib==3.1.3
    - python-spams>=2.6.1
    - openjdk==8.0.152
    - pytorch==1.9.0
    - h5py==3.1.0
    - dask==2021.7.1
    - pydicom==2.1.2
    - pytest>=6.2.2
    - pre-commit==2.13.0
    - pip:
        - opencv-contrib-python==4.5.3.56
        - openslide-python==1.1.2
        - javabridge==1.0.19
        - python-bioformats==4.0.0
        - scanpy==1.7.2
        - anndata==0.7.6
        - deepcell>=0.9.0
        - cellpose>=0.6.1
        - tensorly==0.6.0
        - ipython>=7.20.0
        - sphinx>=3.4.3
        - nbsphinx>=0.8.1
        - nbsphinx-link>=1.3.0
        - sphinx-rtd-theme>=0.5.1
